### ISSUE TITLE
OWASP_MAS_Checklist issue

### ISSUE THREAD

**Issue by SenninSage333** [OWASP/owasp-mastg#2415] opened 2023-05-19 09:28 UTC
Hey,

Do you plan to release newer version of OWASP MAS Checklist?
I am asking because I have a strange issue.
In the current version when I select an answer in the first point for MASVS-STORAGE-1, the color is generated few positions above the row as presented in below screen.
Does someone have similar issue?

![checklist](https://github.com/OWASP/owasp-mastg/assets/58287037/7ecfc064-ea4c-4fd4-abc4-b68663befb8f)

**Comment by bl13pbl03p** [comment] 2023-05-19 10:45
I have the same issue within every tab in the excel file

**Comment by cpholguera** [comment] 2023-05-19 11:26
The excel file is 100 % automatically generated. Here are the relevant scripts

https://github.com/OWASP/owasp-mastg/blob/master/tools/scripts/yaml_to_excel.py

https://github.com/OWASP/owasp-mastg/blob/master/tools/scripts/excel_styles_and_validation.py

You can open a pull request by following these instructions: https://mas.owasp.org/contributing/3_PRs_and_Reviews/

**Comment by cpholguera** [comment] 2023-05-19 11:27
@bl13pbl03p would you like me to assign the issue to you?

**Comment by cpholguera** [comment] 2023-05-19 11:43
I've assigned to you @bl13pbl03p based on your other message. Thanks for helping out!

**Comment by bl13pbl03p** [comment] 2023-05-19 11:44
@cpholguera I will do my best to fix it, but no guarantees can be given 😅. To confirm, all the rows that do not contain a L1, L2 or R value should not have a status column right? For example:

![Screenshot 2023-05-19 at 13 43 14](https://github.com/OWASP/owasp-mastg/assets/22095577/f7545ebe-9cff-4c46-87c3-edfa655d9787)

**Closed** 2023-05-22 19:14 UTC

**Comment by cpholguera** [comment] 2023-05-22 19:45
@SenninSage333, @bl13pbl03p, thank you very much for your help. I've fixed the rest of the issues mentioned and now the sheet cell validation should be working fine. Please take a look by downloading it here: https://mas.owasp.org/MAS_checklist/

**Comment by bl13pbl03p** [comment] 2023-05-23 06:32
@cpholguera Don't thank us yet, it seems a new bug has been born :(

![Screenshot 2023-05-23 at 08 27 15](https://github.com/OWASP/owasp-mastg/assets/22095577/660e3071-c47b-4b08-8991-21cb8355140f)

**Comment by cpholguera** [comment] 2023-05-24 17:41
Thank you@bl13pbl03p, I tried on Google Sheets and Apple Numbers and I can't reproduce the issue, I don't have Excel unfortunately. Could you provide more details on how you got that to show?

**Comment by bl13pbl03p** [comment] 2023-05-26 09:49
@cpholguera 
1. Open the document in Excel via onedrive or via the Excel client application
2. Change status of initial column
3. Coloured column appears two rows above (I11)

Maybe the issue can be fixed by adjusting the status_cells value again (change value from I11 to I13), I will make a pull request

**Comment by bl13pbl03p** [comment] 2023-05-26 12:33
Hmm, the following shows up in Excel. Color and aligning is only applied to the second row above the column itself.

![Screenshot 2023-05-26 at 14 27 53](https://github.com/OWASP/owasp-mastg/assets/22095577/e971a0f5-2745-4156-aabe-8bdc3d4bacf2)

**Comment by cpholguera** [comment] 2023-06-01 02:41
@sushi2k I won't be able to take a look at this in the upcoming weeks. If you have some time and access to excel, would you mind taking a look at this issue and support @bl13pbl03p? Thanks in advance!
